### ISSUE TITLE
Too many C++ warnings

### ISSUE THREAD

**Issue by pbtoast** [pbtoast/polytope#8]
I'm seeing tons of warnings in various source files during the build. It would be nice to get rid of these.

**Comment by jmikeowen** [comment]
I certainly second this.  A lot of these warnings are kind of noise (like unused typedefs).  Some others are complaining about deceptive indendation which is a result of using macros like POLY_CONTRACT_BEGIN_SCOPE.  Not sure how to solve that.

**Comment by pbtoast** [comment]
Well, given that these warnings are intended to help us, I say we disable the noisy ones and focus on fixing the meaningful ones. Every warning can be disabled with a flag (like -Wno-xxxx).

**Comment by pbtoast** [comment]
I'm closing this issue, since the remaining warnings actually do look like things we should fix.
